#!/usr/bin/env node
/**
 * CartKey Store Location Importer
 * 
 * Fetches grocery store locations from OpenStreetMap Overpass API
 * and outputs a TypeScript file with StoreLocation entries.
 *
 * Usage:
 *   npx tsx scripts/import-stores.ts --state VA --radius 100
 *   npx tsx scripts/import-stores.ts --bbox 38.0,-78.0,39.5,-76.5
 *
 * Requires: npm install tsx (for running TypeScript directly)
 */

const OVERPASS_API = 'https://overpass-api.de/api/interpreter';

// Map OSM brand names to CartKey chain IDs
const BRAND_MAP: Record<string, string> = {
  'kroger': 'kroger',
  'safeway': 'safeway',
  'walmart': 'walmart',
  'walmart supercenter': 'walmart',
  'walmart neighborhood market': 'walmart',
  'target': 'target',
  'costco': 'costco',
  'costco wholesale': 'costco',
  "trader joe's": 'traderjoes',
  'whole foods': 'wholefds',
  'whole foods market': 'wholefds',
  'aldi': 'aldi',
  'publix': 'publix',
  'h-e-b': 'heb',
  'heb': 'heb',
  'wegmans': 'wegmans',
  'harris teeter': 'harristeeter',
  'food lion': 'foodlion',
  'giant food': 'giantfood',
  'giant': 'giantfood',
  'lidl': 'lidl',
};

interface OverpassElement {
  type: string;
  id: number;
  lat?: number;
  lon?: number;
  center?: { lat: number; lon: number };
  tags?: Record<string, string>;
}

async function fetchStores(bbox: string): Promise<OverpassElement[]> {
  // Query for shops tagged as supermarket, convenience, or grocery
  const query = `
    [out:json][timeout:60];
    (
      node["shop"="supermarket"](${bbox});
      way["shop"="supermarket"](${bbox});
      node["shop"="grocery"](${bbox});
      way["shop"="grocery"](${bbox});
    );
    out center;
  `;

  const response = await fetch(OVERPASS_API, {
    method: 'POST',
    body: `data=${encodeURIComponent(query)}`,
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  });

  if (!response.ok) throw new Error(`Overpass API returned ${response.status}`);
  const data = await response.json();
  return data.elements;
}

function matchChain(tags: Record<string, string>): string | null {
  const brand = (tags.brand || tags.name || '').toLowerCase().trim();
  for (const [key, chainId] of Object.entries(BRAND_MAP)) {
    if (brand.includes(key)) return chainId;
  }
  return null;
}

function generateId(chainId: string, lat: number, lng: number): string {
  const latStr = lat.toFixed(3).replace('.', '');
  const lngStr = Math.abs(lng).toFixed(3).replace('.', '');
  return `${chainId}-${latStr}-${lngStr}`;
}

async function main() {
  const args = process.argv.slice(2);
  
  // Default: Northern Virginia / DC metro bounding box
  let bbox = '38.0,-77.8,39.2,-76.8';
  
  const bboxIdx = args.indexOf('--bbox');
  if (bboxIdx !== -1 && args[bboxIdx + 1]) {
    bbox = args[bboxIdx + 1];
  }

  console.log(`Fetching grocery stores in bbox: ${bbox}`);
  const elements = await fetchStores(bbox);
  console.log(`Found ${elements.length} grocery stores`);

  const locations: { id: string; chainId: string; name: string; address: string; lat: number; lng: number }[] = [];

  for (const el of elements) {
    const tags = el.tags || {};
    const chainId = matchChain(tags);
    if (!chainId) continue;

    const lat = el.lat ?? el.center?.lat;
    const lng = el.lon ?? el.center?.lon;
    if (!lat || !lng) continue;

    const name = tags.name || tags.brand || chainId;
    const address = [tags['addr:housenumber'], tags['addr:street'], tags['addr:city'], tags['addr:state'], tags['addr:postcode']]
      .filter(Boolean).join(', ') || 'Address not available';

    locations.push({
      id: generateId(chainId, lat, lng),
      chainId,
      name,
      address,
      lat: parseFloat(lat.toFixed(6)),
      lng: parseFloat(lng.toFixed(6)),
    });
  }

  console.log(`Matched ${locations.length} stores to known chains`);
  console.log('Chains:', [...new Set(locations.map((l) => l.chainId))].join(', '));

  // Output TypeScript
  const ts = `// Auto-generated by scripts/import-stores.ts on ${new Date().toISOString()}
// Source: OpenStreetMap Overpass API (bbox: ${bbox})
// Total: ${locations.length} locations

import type { StoreLocation } from './storeLocations';

export const IMPORTED_LOCATIONS: StoreLocation[] = ${JSON.stringify(locations, null, 2)};
`;

  const outPath = 'src/data/storeLocations.imported.ts';
  const fs = await import('fs');
  fs.writeFileSync(outPath, ts);
  console.log(`Written to ${outPath}`);
}

main().catch(console.error);
